### ISSUE TITLE
About the annotation datasets

### ISSUE THREAD

**Issue by gentlefress** [Pointcept/GPT4Point#19]
Dear author,

This is a great work! And I have a question: how can I get the annotation datasets, such as cap3d_caption_train.json.

**Comment by Qi-Zhangyang** [comment]
You can run the code directly and it will be downloaded automatically through the hugging face. 

Of course, you can download it through [hugging face](https://huggingface.co/datasets/alexzyqi/GPT4Point) mannually.

**Comment by gentlefress** [comment]
Thank you for the answer!

**Comment by gentlefress** [comment]
Sorry. I can't download cap3d_caption_train.json with some mistakes, can you share a file or a link?

**Comment by Qi-Zhangyang** [comment]
https://huggingface.co/datasets/alexzyqi/GPT4Point


This is the link to download.

**Comment by gentlefress** [comment]
Thanks

**Comment by gentlefress** [comment]
Hi author, did you release the evaluation code of zero-shot classification and point-text retrieval?
