### ISSUE TITLE
Can't train stage 2

### ISSUE THREAD

**Issue by zoesoon** [Pointcept/GPT4Point#22]
when run  stage 2 training,
Not Found for url: https://hf-mirror.com/alexzyqi/GPT4Point/resolve/main/gpt4point_pretrain_stage1_cap3d.pth

**Comment by Qi-Zhangyang** [comment]
I will check it as soon as possible.

**Comment by Qi-Zhangyang** [comment]
Is there some error in the code, I will update GPT4Point++ code in Aug 8th.

**Comment by Yuehongzhe** [comment]
> Is there some error in

> Is there some error in the code, I will update GPT4Point++ code in Aug 8th.

我有相同的问题，不能训练阶段2，请问是否有更新，谢谢
