### ISSUE TITLE
Evaluate error

### ISSUE THREAD

**Issue by zoesoon** [Pointcept/GPT4Point#24]
when use lavis/output/GPT4Point/pretrain_stage2_cap3d_opt2.7b/20240612103/checkpoint_9.pth as checkpoint,raise KeyError: "Key 'point_encoder.cls_token' not found in checkpoint and does not match any special endings."

**Comment by zoesoon** [comment]
when use lavis/output/GPT4Point/pretrain_stage2_cap3d_opt2.7b/20240612103/checkpoint_9.pth as checkpoint,raise KeyError: "Key 'point_encoder.cls_token' not found in checkpoint and does not match any special endings."

**Comment by Qi-Zhangyang** [comment]
Is there some error in the code, I will update GPT4Point++ code in Aug 8th.

**Comment by JAMESYJL** [comment]
我现在还遇到了这个问题，请问你们的GPT4Point++发布了吗
