### ISSUE TITLE
A Kind Request for Citing our Point-Bind Project

### ISSUE THREAD

**Issue by ZrrSkywalker** [Pointcept/GPT4Point#8]
Hi, thanks for this great project PointBLIP that directly aligns 3D with LLM!

Here is our project [Point-Bind](https://github.com/ZrrSkywalker/Point-Bind) that **first aligns 3D point clouds with LLM and other modalities**, which is released in June, 2023. We also conduct 3D question answering, 3D retrieval and text-3D generation tasks. Given the high similarity of our two projects concerning idea (3D LLM) and implementation (a projection layer), **we would be highly appreciated that you can consider citing our project. We will also cite yours.**

The characters of Point-Bind are as follows:
<img width="983" alt="character" src="https://github.com/Pointcept/PointBLIP/assets/54577425/ec8e6b36-b793-49f2-a2ad-04026737b890">

The following are our examples of 3D question answering:
<div align=center>
<img width="574" alt="Point-LLM" src="https://github.com/Pointcept/PointBLIP/assets/54577425/60108d0c-d431-4629-9f54-941ee4ad541b">
</div>

Thanks very much for your understanding!

**Comment by Qi-Zhangyang** [comment]
Thank you very much for your attention. **PointBind is an excellent project**. We believe it has made a significant contribution to aligning point cloud and text modalities. The reason we didn't initially provide a citation is that PointBind was originally affiliated with llama-adapter (ImageBing-LLM). Later, it transitioned to OpenGVlab, and we couldn't locate a suitable citation path at that time.

**We will soon update the GitHub page, further improving the code and resolving citation issues.** We hope to contribute to the point cloud community together with you.

**Comment by ZrrSkywalker** [comment]
We sincerely appreciate your understanding :). Hope to make the 3D community better together with you!
